services:
  backend:
    build: ./
    container_name: junction
    ports:
      - '8080:8080'
    networks:
      - febnine-net
  local-db:
    image: library/mysql:5.7
    container_name: junction
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Yydo0825..junction
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/x86_64
    networks:
      - febnine-net
  networks:
    febnine-net:

